{% set version = "2.1.2" %}

package:
  name: pendulum
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pendulum/pendulum-{{ version }}.tar.gz
  sha256: b06a0ca1bfe41c990bbf0c029f0b6501a7f2ec4e38bfec730712015e8860f207

build:
  number: 6
  script:
    - export PENDULUM_EXTENSIONS=1  # [not win]
    - set PENDULUM_EXTENSIONS=1  # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - poetry-core >=1.0.0a9
    - {{ compiler('c') }}
  run:
    - python
    - python-dateutil >=2.6,<3.0
    - pytzdata >=2020.1

test:
  requires:
    - pip
  commands:
    - pip check
    # make sure the extensions actually built (this might be fragile since these modules are private)
    - python -c "from pendulum.parsing._iso8601 import parse_iso8601"  # [python_impl == 'cpython']
    - python -c "from pendulum._extensions._helpers import days_in_year"  # [python_impl == 'cpython']
  imports:
    - pendulum
about:
  home: https://pendulum.eustace.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python datetimes made easy
  description: |
    Drop-in replacement for the standard datetime class.
    It behaves exactly like it but with many improvements.
  doc_url: https://pendulum.eustace.io/docs/
  dev_url: https://github.com/sdispater/pendulum

extra:
  recipe-maintainers:
    - mcs07
    - ocefpaf
    - xylar
