{% set name = "pendulum" %}
{% set version = "3.0.0" %}

package:
  name: pendulum
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pendulum-{{ version }}.tar.gz
  sha256: 5d034998dea404ec31fae27af6b22cff1708f830a1ed7353be4d1019bb9f584e
  patches:
    - 0001-remove-tzdata-dep-for-pip-check.patch

build:
  number: 0
  missing_dso_whitelist:
    - '*/libgcc_s.so.1'
    - '*/librt.so.1'
    - '*/libpthread.so.0'
    - '*/libm.so.6'
    - '*/libc.so.6'

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.0,<2.0                     # [build_platform != target_platform]
    - {{ compiler('rust') }}
  host:
    - python
    - maturin >=1.0,<2.0
    - poetry-core
    - pip
  run:
    - python
    - python-dateutil >=2.6
    - tzdata >=2020.1
    - backports.zoneinfo >=0.2.1  # [py<39]
    - time-machine >=2.6.0  # [python_impl == 'cpython']
    - importlib-resources >=5.9.0  # [py<39]
    - libgcc-ng

test:
  requires:
    - pip
  commands:
    - pip check
    # make sure the extensions actually built (this might be fragile since these modules are private)
    - python -c "from pendulum._pendulum import parse_iso8601"  # [python_impl == 'cpython']
    - python -c "from pendulum._helpers import days_in_year"  # [python_impl == 'cpython']
  imports:
    - pendulum
about:
  home: https://pendulum.eustace.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python datetimes made easy
  description: |
    Drop-in replacement for the standard datetime class.
    It behaves exactly like it but with many improvements.
  doc_url: https://pendulum.eustace.io/docs/
  dev_url: https://github.com/sdispater/pendulum

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/48409
    reason: Dependency for microsoft-kiota-serialization-json
    recipe-maintainers:
      - ianaobi

  recipe-maintainers:
    - ocefpaf
    - xylar
