appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: EscHNzb2gDAb4K6T+peJ3NhRAU5XwB2803oW7JYkmqiJyGLhK+kfunX07qJ6/wJQesHj/kSrWJrCC3wgzy9QvWSw0bm25ejn/6Q5YKb7x8HGIRfS2ijm4wPUxT91BqT8T6oEqaZBZBUBTjau2/gs1+uOpvGGvSJgy884OH6o5ev+W9sBo5pxi4BRr/RJxA+kNrNGNUXFumJl/1FBq01ewi15so/mwFBUWRV5R9X3QWe7EmV+i9NZMW7eqoKN815yrHqwJqgz343+x7QFQHHGuYG7DQruvS5GN6OEBvNCWl3Gw0/GVdC0/J8kzgYnMCYyjbo6lQHxxwbvnyK5LMc9h12lSY3iGoo77L/fn5sZlAwxg3eDsHS33tDl8LNYL29c7TTqPr5PteKPIpyfFqj158qIM43ou7kqXX5jL+fhXNIAaE9p+GtIXBMxz6vx7XxqS5F2qhOCQi5Fsu6+H3NGJZ1eHNPz6nK40xaSqwhvT+jVyp4rKVVLumOVJq28Ta4QfRPic4ZKRAkpZoSJRTc2td1LO0SzuTCceK7D7HXbvlQMWIv9GB59I5lyCFfHspc24FjJn93MipfO7xutScBGoJi+rQ86nYxn1T2xHafR0djyEmCqE3nNNuTIoGpcZvXDQR9t2f+Wb9TVytbC8VwCg06Y+rQjJGNhPwkjRRUvT70=}
provider:
  win: azure
conda_forge_output_validation: true
